driver:
  name: vagrant
  customize:
    cpus: 2
    memory: 1024
  network:
  - ["forwarded_port", {guest: 8080, host: 9090, auto_correct: true}]

provisioner:
  name: chef_zero
  require_chef_omnibus: 11.8.0
  data_path: test/shared

platforms:
  - name: ubuntu-12.04
    run_list: apt::default

suites:
  #
  # Command suites
  #
  - name: jenkins_command_execute
    run_list: jenkins_command::execute

  #
  # Credentials suites
  #
  - name: jenkins_credentials_create
    run_list: jenkins_credentials::create
  - name: jenkins_credentials_delete
    run_list: jenkins_credentials::delete

  #
  # Job suites
  #
  - name: jenkins_job_create
    run_list: jenkins_job::create
  - name: jenkins_job_delete
    run_list: jenkins_job::delete
  - name: jenkins_job_disable
    run_list: jenkins_job::disable
  - name: jenkins_job_enable
    run_list: jenkins_job::enable

  #
  # Plugin suites
  #
  - name: jenkins_plugin_disable
    run_list: jenkins_plugin::disable
  - name: jenkins_plugin_enable
    run_list: jenkins_plugin::enable
  - name: jenkins_plugin_install
    run_list: jenkins_plugin::install
  - name: jenkins_plugin_uninstall
    run_list: jenkins_plugin::uninstall

  #
  # Slave suites
  #
  - name: jenkins_slave_create
    run_list: jenkins_slave::create
  - name: jenkins_slave_delete
    run_list: jenkins_slave::delete
  - name: jenkins_slave_connect
    run_list: jenkins_slave::connect
  - name: jenkins_slave_disconnect
    run_list: jenkins_slave::disconnect
  - name: jenkins_slave_online
    run_list: jenkins_slave::online
  - name: jenkins_slave_offline
    run_list: jenkins_slave::offline

  #
  # User suites
  #
  - name: jenkins_user_create
    run_list: jenkins_user::create
  - name: jenkins_user_delete
    run_list: jenkins_user::delete
