---
driver:
  name: rackspace
  require_chef_omnibus: '11.8.2'
  rackspace_username: <%= ENV['rackspace_username'] %>
  rackspace_api_key:  <%= ENV['rackspace_api_key'] %>
  rackspace_region: 'lon'
  public_key_path: <%= ENV['sshpubkey'] %>
  ssh_key: <%= ENV['ssh_key'] %>

platforms:
- name: centos-6.4
  driver_config:
    image_id: 'f70ed7c7-b42e-4d77-83d8-40fa29825b85'
  run_list:
    - recipe[rackspace_yum]
- name: ubuntu-12.04
  driver_config:
    image_id: '80fbcb55-b206-41f9-9bc2-2dd7aac6c061'
  run_list:
  - recipe[rackspace_apt]
- name: debian-7.2
  driver_config:
    image_id: '857d7d36-34f3-409f-8435-693e8797be8b'
  run_list:
    - recipe[rackspace_apt]

suites:
  - name: jenkins_master
    run_list:
    - recipe[jenkins::server]
    attributes:
      jenkins:
        server:
          pubkey: /var/lib/jenkins/.ssh/id_rsa.pub
          install_method: package
          plugins:
          - name: git-client
            version: 1.0.5
          - name: git
            version: 1.3.0
  - name: jenkins_slave
    run_list:
    - recipe[jenkins::node]
    attributes:
      jenkins:
        server:
          url: http://162.13.153.55:8080
        node:
          executors: 2
          name: slave01
          agent_type: jnlp
          home: /home/jenkins

  - name: jenkins_slave2
    run_list:
    - recipe[jenkins::node]
    attributes:
      jenkins:
        server:
          url: http://162.13.153.55:8080
        node:
          executors: 2
          name: slave02
          agent_type: jnlp
          home: /home/jenkins
