AllCops:
  Excludes:
    - vendor/**

AlignParameters:
  Enabled: false
Encoding:
  Enabled: false
HashSyntax:
  Enabled: false
LineLength:
  Enabled: false
ClassLength:
  Enabled: false
MethodLength:
  Enabled: false
Documentation:
  Enabled: false
