AllCops:
  Exclude:
    - vendor/**

ClassLength:
  Enabled: false
ClassAndModuleChildren:
  Enabled: false
Documentation:
  Enabled: false
DoubleNegation:
  Enabled: false
Encoding:
  Enabled: false
LineLength:
  Enabled: false
MethodLength:
  Enabled: false
SingleSpaceBeforeFirstArg:
  Enabled: false
TrailingComma:
  EnforcedStyleForMultiline: comma
